# 
#《https://github.com/KFERMercer/OpenWrt-CI》
#
#版权所有2019年第三季度
#
#版权所有2020年KFERMercer
#
名字: OpenWrt-CI

在:
日程安排:
    - 时间单位: 0 20 * * *

   释放；排放；发布:
类型: [出版]

工作:

build_openwrt:

名字: 构建OpenWrt固件

连续运行: Ubuntu-最新版

步伐:
      - 名字: 空间清理和初始化环境
包封/包围（动词包围的简写):
DEBIAN_FRONTEND: 非交互的
奔跑: |
码头工人图像问
sudo-E RM-RF/usr/share/dot net/etc/MySQL/etc/PHP/etc/apt/sources。列表。d/usr/本地/lib/Android
sudo-E apt-mark hold gr B- EFI-amd64-已签名
sudo -E apt更新
sudo-E apt-y purge azure-CLI * docker * ghc * Zulu * llvm * Firefox Google * dot net * powershell * open JDK * MySQL * PHP * MongoDB * dot net * snap *
sudo -E apt -y全面升级
sudo-E apt-y install ack antlr 3 aria 2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fast jar flex gawk gettext gcc-multi lib g++-multi lib git gperf have ged help 2 man intl tool libc 6-dev-i386 libelf-dev libglib 2.0-dev lib GMP 3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses 5-dev lib
sudo -E系统守护程序-重新加载
sudo -E apt -y自动移除-清除
苏多伊易于清洁
须藤街时间日期设置-时区"亚洲/上海"

      - 名字: 检出OpenWrt
使用: 动作/签出@v3

      - 名字: 更新订阅源
奔跑: |
sed-I‘s/# src-git hello world/src-git hello world/g。/feeds.conf.default
。/脚本/源更新［构成动植物的古名或拉丁化的现代名］
。/脚本/提要安装［构成动植物的古名或拉丁化的现代名］

      - 名字: 生成配置文件
奔跑: 进行定义配置

      - 名字: 下载软件包
奔跑: 制作下载-j16

      - 名字: 编译固件
奔跑: |
make-j $（nproc）| | make-J1 V = s
echo“= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =“
回显"空间使用情况:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
